### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by MercureTony** [bulby97/bible-strong#29]
Bonjour, y a pas longtemps je cherchais une application pour étudier la bible dans sa langue originale (hébreux et grec) et je suis tombé sur votre application et j'ai vraiment aimé! 

Merci beaucoup pour cette application! Ça non seulement été très bien fait mais c'est aussi très utile pour moi qui fait des études et cherches à davantage connaître le Seigneur.

Aujourd'hui, en cherchant à vous contacter, j'ai trouvé que vous avez un repo Github. Et je me demandais si je pourrais vous aider ou contribuer dans quoique ce soit.

De plus, je compte aussi créer des applications pour des chrétiens et j'ai débuté récemment React Native.

Merci beaucoup pour votre retour.

**Comment by bulby97** [comment]
Bonjour Tony, avec grand plaisir.

À quel niveau êtes-vous dans le React-Native ?

J'ai un trello avec pas mal de fonctionnalité : https://trello.com/b/BHfLCWtv/bible-strong-roadmap
Vous pouvez m'envoyer un mail pour qu'on puisse discuter / s'appeler plus amplement pour travailler dessus :)

**Comment by MercureTony** [comment]
Bonjour! Et merci de votre retour!

À date, je débute dans React-Native (donc un je suis débutant). Mais, j'avance vite toutefois à cause de la familiarité que j'ai avec JavaScript, HTML5 et CSS3. 

J'ai aussi regardé votre trello, et c'est vraiment très intéréssant tout ce que vous faites et comptez faire à travers cette application! Que Dieu puisse davantage bénir ce projet! 

J'aimerai aussi mettre mes talents au profit du corps de Christ également! C'est vraiment très encourageant tout ce que je vois! 

Anthony

**Comment by bulby97** [comment]
Hello Anthony, merci de ta réponse, contacte par mail et je t'envoie tous les fichiers nécessaires au lancement de l'app ;)
